site_name: FileClassify

theme:
  name: material
  palette:
    primary: purple
    accent: light purple
  font:
    text: Open Sans
    code: Roboto Mono

plugins:
  - mkdocstrings
  - search

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Explanation: explanation.md
  - Examples: examples.md
  - API Reference: api.md
  - Tutorials: tutorials.md
  - Reference: reference.md
  - Contacts: contacts.md
